services:
  sisgea-module-sisgha:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: sisgea-module-sisgha
    working_dir: /sisgea/env-dev/modules/back-end/module-sisgha
    depends_on:
      - sisgea-module-sisgha-db
    networks:
      - sisgea-net
    ports:
      - 127.128.77.10:3477:3477
      - 127.128.77.10:9229:9229
    volumes:
      - ../../../../../libs:/sisgea/env-dev/libs
      - ../../:/sisgea/env-dev/modules/back-end/module-sisgha
    env_file:
      - .env

  sisgea-module-sisgha-db:
    image: bitnami/postgresql:15
    container_name: sisgea-module-sisgha-db
    volumes:
      - 'sisgea-module-sisgha-db-data:/bitnami/postgresql'
      - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - sisgea-net
    ports:
      - 127.128.77.11:5432:5432
    env_file:
      - .db.env

networks:
  sisgea-net:
    external: true

volumes:
  sisgea-module-sisgha-db-data:
